blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/tallguyjenks/PyRM/discussions
    about: Please ask and answer questions here.
  - name: Security Concern
    url: https://github.com/tallguyjenks/PyRM/security/policy
    about: Please report security vulnerabilities here.
